#include "Precompiled.h"
#include "StaticSampler.h"

/*
	static const StaticSampler PointWrap;
	static const StaticSampler PointClamp;
	static const StaticSampler LinearWrap;
	static const StaticSampler LinearClamp;
	static const StaticSampler AnisotropicWrap;
	static const StaticSampler AnisotropicClamp;
	static const StaticSampler Default;

*/


const StaticSampler StaticSampler::PointWrap
(
	0,
	D3D12_FILTER_COMPARISON_MIN_MAG_MIP_POINT,
	D3D12_TEXTURE_ADDRESS_MODE_WRAP,
	D3D12_TEXTURE_ADDRESS_MODE_WRAP,
	D3D12_TEXTURE_ADDRESS_MODE_WRAP,
	0.0f,
	16,
	D3D12_COMPARISON_FUNC_LESS_EQUAL,
	D3D12_STATIC_BORDER_COLOR_OPAQUE_WHITE,
	0.0f,
	D3D12_FLOAT32_MAX,
	D3D12_SHADER_VISIBILITY_ALL,
	0
);


const StaticSampler StaticSampler::PointClamp
(
	0,
	D3D12_FILTER_COMPARISON_MIN_MAG_MIP_POINT,
	D3D12_TEXTURE_ADDRESS_MODE_CLAMP,
	D3D12_TEXTURE_ADDRESS_MODE_CLAMP,
	D3D12_TEXTURE_ADDRESS_MODE_CLAMP,
	0.0f,
	16,
	D3D12_COMPARISON_FUNC_LESS_EQUAL,
	D3D12_STATIC_BORDER_COLOR_OPAQUE_WHITE,
	0.0f,
	D3D12_FLOAT32_MAX,
	D3D12_SHADER_VISIBILITY_ALL,
	0
);


const StaticSampler StaticSampler::LinearWrap
(
	0,
	D3D12_FILTER_COMPARISON_MIN_MAG_MIP_LINEAR,
	D3D12_TEXTURE_ADDRESS_MODE_WRAP,
	D3D12_TEXTURE_ADDRESS_MODE_WRAP,
	D3D12_TEXTURE_ADDRESS_MODE_WRAP,
	0.0f,
	16,
	D3D12_COMPARISON_FUNC_LESS_EQUAL,
	D3D12_STATIC_BORDER_COLOR_OPAQUE_WHITE,
	0.0f,
	D3D12_FLOAT32_MAX,
	D3D12_SHADER_VISIBILITY_ALL,
	0
);


const StaticSampler StaticSampler::LinearClamp
(
	0,
	D3D12_FILTER_COMPARISON_MIN_MAG_MIP_LINEAR,
	D3D12_TEXTURE_ADDRESS_MODE_CLAMP,
	D3D12_TEXTURE_ADDRESS_MODE_CLAMP,
	D3D12_TEXTURE_ADDRESS_MODE_CLAMP,
	0.0f,
	16,
	D3D12_COMPARISON_FUNC_LESS_EQUAL,
	D3D12_STATIC_BORDER_COLOR_OPAQUE_WHITE,
	0.0f,
	D3D12_FLOAT32_MAX,
	D3D12_SHADER_VISIBILITY_ALL,
	0
);


const StaticSampler StaticSampler::AnisotropicWrap
(
	0,
	D3D12_FILTER_COMPARISON_ANISOTROPIC,
	D3D12_TEXTURE_ADDRESS_MODE_WRAP,
	D3D12_TEXTURE_ADDRESS_MODE_WRAP,
	D3D12_TEXTURE_ADDRESS_MODE_WRAP,
	0.0f,
	16,
	D3D12_COMPARISON_FUNC_LESS_EQUAL,
	D3D12_STATIC_BORDER_COLOR_OPAQUE_WHITE,
	0.0f,
	D3D12_FLOAT32_MAX,
	D3D12_SHADER_VISIBILITY_ALL,
	0
);


const StaticSampler StaticSampler::AnisotropicClamp
(
	0,
	D3D12_FILTER_COMPARISON_ANISOTROPIC,
	D3D12_TEXTURE_ADDRESS_MODE_CLAMP,
	D3D12_TEXTURE_ADDRESS_MODE_CLAMP,
	D3D12_TEXTURE_ADDRESS_MODE_CLAMP,
	0.0f,
	16,
	D3D12_COMPARISON_FUNC_LESS_EQUAL,
	D3D12_STATIC_BORDER_COLOR_OPAQUE_WHITE,
	0.0f,
	D3D12_FLOAT32_MAX,
	D3D12_SHADER_VISIBILITY_ALL,
	0
);


const StaticSampler StaticSampler::Default(PointWrap);